name: Deploy to Hf Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "*.md"

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          lfs: true
          ref: main

      - name: Sync to HF Space
        uses: huggingface/hub-sync@fdffea8e04104d0bd4e3181c5feb3025f0433ff5 # v0.3.0
        with:
          github_repo_id: huggingface/lerobot-dataset-visualizer
          huggingface_repo_id: lerobot/visualize_dataset
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
